name: Local Deploy to S3
on:
  push:
    branches:
      - 'main'
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.LOCAL_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.LOCAL_AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.LOCAL_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.LOCAL_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.LOCAL_S3_BUCKET_REGION }}

      - name: Deploy
        run: aws s3 sync . s3://${{ secrets.LOCAL_S3_BUCKET }}/documentation --exclude '.git/*' --delete
  
